<a href="https://colab.research.google.com/github/Leonela180/Panda/blob/main/examen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# PARTE 1

In [ ]:
# 1. Crea un arreglo NumPy de dimensión 1 con los números del 1 al 20.
arreglo_1_a_20 = np.arange(1, 21)
print("Arreglo del 1 al 20:")
display(arreglo_1_a_20)

Arreglo del 1 al 20:


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# 2. Selecciona los múltiplos de 3 de ese arreglo y muéstralos.
multiplos_de_3 = arreglo_1_a_20[arreglo_1_a_20 % 3 == 0]
print("\nMúltiplos de 3 del arreglo:")
display(multiplos_de_3)


Múltiplos de 3 del arreglo:


array([ 3,  6,  9, 12, 15, 18])

In [ ]:
# 3. Genera una matriz aleatoria de tamaño 5x5 con números entre 0 y 1.
matriz_aleatoria = np.random.rand(5, 5)
print("\nMatriz aleatoria 5x5:")
display(matriz_aleatoria)


Matriz aleatoria 5x5:


array([[0.16580695, 0.62861055, 0.90843419, 0.99506312, 0.15406861],
       [0.37314497, 0.59180095, 0.87352067, 0.52608015, 0.22424424],
       [0.12737689, 0.08838887, 0.28422279, 0.28046617, 0.46636996],
       [0.15117043, 0.07577753, 0.41469499, 0.76672869, 0.47196421],
       [0.89601882, 0.29465579, 0.67041022, 0.53943468, 0.66455741]])

In [ ]:
# 4. Calcula la media, la desviación estándar y el valor máximo de esa matriz.
media_matriz = np.mean(matriz_aleatoria)
desviacion_estandar_matriz = np.std(matriz_aleatoria)
maximo_matriz = np.max(matriz_aleatoria)

print(f"\nMedia de la matriz: {media_matriz}")
print(f"Desviación estándar de la matriz: {desviacion_estandar_matriz}")
print(f"Valor máximo de la matriz: {maximo_matriz}")


Media de la matriz: 0.465320474278437
Desviación estándar de la matriz: 0.276562808967207
Valor máximo de la matriz: 0.9950631187556879


In [ ]:
# 5. Transforma la matriz en un vector de una sola dimensión.
vector_plano = matriz_aleatoria.flatten()
print("\nMatriz transformada en vector de una dimensión:")
display(vector_plano)


Matriz transformada en vector de una dimensión:


array([0.16580695, 0.62861055, 0.90843419, 0.99506312, 0.15406861,
       0.37314497, 0.59180095, 0.87352067, 0.52608015, 0.22424424,
       0.12737689, 0.08838887, 0.28422279, 0.28046617, 0.46636996,
       0.15117043, 0.07577753, 0.41469499, 0.76672869, 0.47196421,
       0.89601882, 0.29465579, 0.67041022, 0.53943468, 0.66455741])

# PARTE 2

## PRIMERA FORMA

In [ ]:
# 1. Crea un DataFrame con los siguientes datos de estudiantes:
data = {'Nombre': ['Ana', 'Luis', 'María', 'Pedro', 'Sofía'],
        'Edad': [20, 21, 19, 22, 20],
        'Nota_Matemáticas': [18, 15, 16, 12, 19],
        'Nota_IA': [17, 14, 18, 13, 20]}
df_estudiantes = pd.DataFrame(data)
print("DataFrame de estudiantes:")
display(df_estudiantes)

DataFrame de estudiantes:


Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20

In [ ]:
# 2. Calcula el promedio de cada columna numérica.
promedio_columnas = df_estudiantes.mean(numeric_only=True)
print("\nPromedio de cada columna numérica:")
display(promedio_columnas)


Promedio de cada columna numérica:


Edad                20.4
Nota_Matemáticas    16.0
Nota_IA             16.4
dtype: float64

In [ ]:
# 3. Filtra los estudiantes con nota de IA mayor a 15.
estudiantes_ia_alta = df_estudiantes[df_estudiantes['Nota_IA'] > 15]
print("\nEstudiantes con nota de IA mayor a 15:")
display(estudiantes_ia_alta)


Estudiantes con nota de IA mayor a 15:


Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
2  María    19                16       18
4  Sofía    20                19       20

In [ ]:
# 4. Agrega una nueva columna llamada Promedio que contenga el promedio de Nota_Matemáticas y Nota_IA.
df_estudiantes['Promedio'] = (df_estudiantes['Nota_Matemáticas'] + df_estudiantes['Nota_IA']) / 2
print("\nDataFrame con columna 'Promedio' agregada:")
display(df_estudiantes)


DataFrame con columna 'Promedio' agregada:


Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19       20      19.5

In [ ]:
# 5. Ordena el DataFrame según la columna Promedio de mayor a menor.
df_ordenado_por_promedio = df_estudiantes.sort_values(by='Promedio', ascending=False)
print("\nDataFrame ordenado por 'Promedio' de mayor a menor:")
display(df_ordenado_por_promedio)


DataFrame ordenado por 'Promedio' de mayor a menor:


Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
4  Sofía    20                19       20      19.5
0    Ana    20                18       17      17.5
2  María    19                16       18      17.0
1   Luis    21                15       14      14.5
3  Pedro    22                12       13      12.5

## SEGUNDA FORMA

In [ ]:
# Cargar los datos desde el archivo CSV
try:
    df_estudiantes_csv = pd.read_csv('estudiantes.csv', encoding='utf-8-sig', sep=';') # Usar 'utf-8-sig' para manejar BOM
    # Dropping the unnamed column that results from extra semicolons
    df_estudiantes_csv = df_estudiantes_csv.loc[:, ~df_estudiantes_csv.columns.str.contains('^Unnamed')]
    # Renombrar las columnas para asegurar que no haya caracteres ocultos
    df_estudiantes_csv.columns = ['Nombre', 'Edad', 'Nota_Matemáticas', 'Nota_IA']
    print("DataFrame de estudiantes cargado desde CSV:")
    display(df_estudiantes_csv)
except Exception as e:
    print(f"Error al cargar o procesar el archivo CSV: {e}")

DataFrame de estudiantes cargado desde CSV:


Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20

In [ ]:
# 2. Calcula el promedio de cada columna numérica.
promedio_columnas_csv = df_estudiantes_csv.mean(numeric_only=True)
print("\nPromedio de cada columna numérica (desde CSV):")
display(promedio_columnas_csv)


Promedio de cada columna numérica (desde CSV):


Edad                20.4
Nota_Matemáticas    16.0
Nota_IA             16.4
dtype: float64

In [ ]:
# 3. Filtra los estudiantes con nota de IA mayor a 15.
estudiantes_ia_alta_csv = df_estudiantes_csv[df_estudiantes_csv['Nota_IA'] > 15]
print("\nEstudiantes con nota de IA mayor a 15 (desde CSV):")
display(estudiantes_ia_alta_csv)


Estudiantes con nota de IA mayor a 15 (desde CSV):


Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
2  María    19                16       18
4  Sofía    20                19       20

In [ ]:
# 4. Agrega una nueva columna llamada Promedio que contenga el promedio de Nota_Matemáticas y Nota_IA.
df_estudiantes_csv['Promedio'] = (df_estudiantes_csv['Nota_Matemáticas'] + df_estudiantes_csv['Nota_IA']) / 2
print("\nDataFrame con columna 'Promedio' agregada (desde CSV):")
display(df_estudiantes_csv)


DataFrame con columna 'Promedio' agregada (desde CSV):


Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19       20      19.5

In [ ]:
# 5. Ordena el DataFrame según la columna Promedio de mayor a menor.
df_ordenado_por_promedio_csv = df_estudiantes_csv.sort_values(by='Promedio', ascending=False)
print("\nDataFrame ordenado por 'Promedio' de mayor a menor (desde CSV):")
display(df_ordenado_por_promedio_csv)


DataFrame ordenado por 'Promedio' de mayor a menor (desde CSV):


Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
4  Sofía    20                19       20      19.5
0    Ana    20                18       17      17.5
2  María    19                16       18      17.0
1   Luis    21                15       14      14.5
3  Pedro    22                12       13      12.5

# PARTE 3

In [ ]:
 #Ejercicio 1
 def analyze_list(numbers):
    if not numbers:
        return None, None, None  # Manejar el caso de lista vacía

    maximum = max(numbers)
    minimum = min(numbers)
    average = sum(numbers) / len(numbers)

    return maximum, minimum, average

# Lista de ejemplo
sample_numbers = [10, 20, 30, 40, 50]

# Llamar a la función e imprimir los resultados
max_val, min_val, avg_val = analyze_list(sample_numbers)

print(f"Lista de ejemplo: {sample_numbers}")
print(f"Máximo: {max_val}")
print(f"Mínimo: {min_val}")
print(f"Promedio: {avg_val}")

Lista de ejemplo: [10, 20, 30, 40, 50]
Máximo: 50
Mínimo: 10
Promedio: 30.0


In [ ]:
#Ejercicio 2
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# Crear el arreglo de entrada
x = np.array([-2, -1, 0, 1, 2])

# Aplicar la función sigmoide al arreglo
sigmoid_x = sigmoid(x)

# Imprimir los arreglos original y resultante
print("Arreglo original:", x)
print("Arreglo activado por sigmoide:", sigmoid_x)

Arreglo original: [-2 -1  0  1  2]
Arreglo activado por sigmoide: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [ ]:
#Ejercicio 3
def classify_students(df):
  # Clasificar estudiantes y agregar columna 'Estado'
  df['Estado'] = np.where(df['Promedio'] >= 14, 'Aprobado', 'Desaprobado')
  return df

# Aplicar la función al DataFrame df_estudiantes (haciendo una copia para no modificar el original)
df_estudiantes_classified = classify_students(df_estudiantes.copy())

# Mostrar el DataFrame actualizado
print("\nDataFrame con columna 'Estado' agregada:")
display(df_estudiantes_classified)


DataFrame con columna 'Estado' agregada:


Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio       Estado
0    Ana    20                18       17      17.5     Aprobado
1   Luis    21                15       14      14.5     Aprobado
2  María    19                16       18      17.0     Aprobado
3  Pedro    22                12       13      12.5  Desaprobado
4  Sofía    20                19       20      19.5     Aprobado

# PARTE 4

In [ ]:
ventas = pd.DataFrame({
    "Producto": ["A", "B", "C", "D", "E"],
    "Ventas_2024": [120, 340, 560,230, 150],
    "Ventas_2025": [200, 400, 600, 300, 180]
})

# 1. Columna de Crecimiento porcentual
ventas["Crecimiento"] = ((ventas["Ventas_2025"] - ventas["Ventas_2024"]) / ventas["Ventas_2024"]) * 100
display(ventas)
print("\n")
# 2. Producto con mayor crecimiento
mayor_crecimiento = ventas.loc[ventas["Crecimiento"].idxmax()]
display(mayor_crecimiento)

Producto  Ventas_2024  Ventas_2025  Crecimiento
0        A          120          200    66.666667
1        B          340          400    17.647059
2        C          560          600     7.142857
3        D          230          300    30.434783
4        E          150          180    20.000000

Producto               A
Ventas_2024          120
Ventas_2025          200
Crecimiento    66.666667
Name: 0, dtype: object

# PARTE 5

In [ ]:
# Ejercicio 1: Resolver ecuaciones lineales
def solve_linear(a, b):
    # Resuelve la ecuación lineal ax + b = 0
    if a == 0:
        # Manejar el caso donde a es cero
        return "Esta no es una ecuación lineal o no tiene solución única."
    else:
        # Calcular el valor de x
        x = -b / a
        return x

# Casos de prueba
print(f"Resolviendo 2x + 4 = 0: x = {solve_linear(2, 4)}")
print(f"Resolviendo 0x + 5 = 0: {solve_linear(0, 5)}")
print(f"Resolviendo 3x - 9 = 0: x = {solve_linear(3, -9)}")

Resolviendo 2x + 4 = 0: x = -2.0
Resolviendo 0x + 5 = 0: Esta no es una ecuación lineal o no tiene solución única.
Resolviendo 3x - 9 = 0: x = 3.0


In [ ]:
import cmath # Importar cmath para soporte de números complejos

# Ejercicio 2: Resolver ecuaciones de segundo grado
def solve_quadratic(a, b, c):
    # Calcular el discriminante (delta)
    delta = (b**2) - 4*(a*c)

    # Encontrar las dos soluciones
    x1 = (-b - cmath.sqrt(delta)) / (2*a)
    x2 = (-b + cmath.sqrt(delta)) / (2*a)

    return x1, x2

# Casos de prueba
print("Resolviendo x² - 5x + 6 = 0:")
sol1, sol2 = solve_quadratic(1, -5, 6)
print(f"Soluciones: x1 = {sol1}, x2 = {sol2}")

print("\nResolviendo x² + 2x + 1 = 0:")
sol1, sol2 = solve_quadratic(1, 2, 1)
print(f"Soluciones: x1 = {sol1}, x2 = {sol2}")

print("\nResolviendo x² + x + 1 = 0:")
sol1, sol2 = solve_quadratic(1, 1, 1)
print(f"Soluciones: x1 = {sol1}, x2 = {sol2}")

Solving x² - 5x + 6 = 0:
Solutions: x1 = (2+0j), x2 = (3+0j)

Solving x² + 2x + 1 = 0:
Solutions: x1 = (-1+0j), x2 = (-1+0j)

Solving x² + x + 1 = 0:
Solutions: x1 = (-0.5-0.8660254037844386j), x2 = (-0.5+0.8660254037844386j)
